# Generated by Django 6.1.1 on 2026-10-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d3c', '0004_alter_filehash_options_alter_hash_options_and_more'),
    ]

    # was added in 0001_initial but used nowhere
    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
